package com.papergenerator.controller;

import com.papergenerator.dto.PptxRequest;
import com.papergenerator.service.PowerPointService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

/**
 * PowerPoint generation API.
 */
@Slf4j
@RestController
@RequestMapping("/api/pptx")
@RequiredArgsConstructor
public class PowerPointController {

    private final PowerPointService powerPointService;

    /**
     * Generate a PPTX file.
     * POST /api/pptx/generate
     */
    @PostMapping("/generate")
    public ResponseEntity<byte[]> generate(@RequestBody PptxRequest req) {
        try {
            byte[] bytes = powerPointService.generatePptx(req);
            String filename = (req.getFilename() != null ? req.getFilename() : "presentation") + ".pptx";
            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
                    .contentType(MediaType.parseMediaType(
                            "application/vnd.openxmlformats-officedocument.presentationml.presentation"))
                    .body(bytes);
        } catch (Exception e) {
            log.error("PPTX generate error", e);
            return ResponseEntity.status(500).build();
        }
    }

    /**
     * Generate a demo PPTX presentation.
     * GET /api/pptx/demo
     */
    @GetMapping("/demo")
    public ResponseEntity<byte[]> demo() {
        try {
            var titleSlide = PptxRequest.SlideRequest.builder()
                    .layout("TITLE").title("Java Paper Generator")
                    .subtitle("Apache POI XSLF Demo")
                    .bgColor("1F3864")
                    .shapes(List.of())
                    .notes("This is a demo presentation generated by the Java Paper Generator API.")
                    .build();

            var contentSlide = PptxRequest.SlideRequest.builder()
                    .layout("TITLE_AND_CONTENT").title("Features")
                    .shapes(List.of(
                            PptxRequest.ShapeRequest.builder()
                                    .type("textbox").text("• Full Apache POI support\n• IEEE paper generation\n• Excel & PowerPoint\n• LaTeX support")
                                    .x(50).y(100).width(860).height(400)
                                    .fontSize(20).fontColor("FFFFFF")
                                    .fillColor("2E75B6")
                                    .build()
                    ))
                    .bgColor("1F3864")
                    .build();

            PptxRequest req = PptxRequest.builder()
                    .filename("demo")
                    .slides(List.of(titleSlide, contentSlide))
                    .build();
            byte[] bytes = powerPointService.generatePptx(req);
            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"demo.pptx\"")
                    .contentType(MediaType.parseMediaType(
                            "application/vnd.openxmlformats-officedocument.presentationml.presentation"))
                    .body(bytes);
        } catch (Exception e) {
            log.error("PPTX demo error", e);
            return ResponseEntity.status(500).build();
        }
    }
}
